// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJ1bAygrBC6EmG8guhDfBqTe753b5gEY',
    appId: '1:490129728013:web:f72943208e74e6d0bf6b44',
    messagingSenderId: '490129728013',
    projectId: 'news-crawler-70b73',
    authDomain: 'news-crawler-70b73.firebaseapp.com',
    storageBucket: 'news-crawler-70b73.firebasestorage.app',
    measurementId: 'G-CVQSQ2BD8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3N0od5T-lPdZzwx8UpnJIlzXphoMd2o',
    appId: '1:490129728013:android:ea847d757e618018bf6b44',
    messagingSenderId: '490129728013',
    projectId: 'news-crawler-70b73',
    storageBucket: 'news-crawler-70b73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARwi4BKd6XkL1VCeX72lB89fHt4Nsi9hk',
    appId: '1:490129728013:ios:4a55ae0487a468f0bf6b44',
    messagingSenderId: '490129728013',
    projectId: 'news-crawler-70b73',
    storageBucket: 'news-crawler-70b73.firebasestorage.app',
    iosBundleId: 'com.amorypaz.newsCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYJ1bAygrBC6EmG8guhDfBqTe753b5gEY',
    appId: '1:490129728013:web:a64bbc2abd673306bf6b44',
    messagingSenderId: '490129728013',
    projectId: 'news-crawler-70b73',
    authDomain: 'news-crawler-70b73.firebaseapp.com',
    storageBucket: 'news-crawler-70b73.firebasestorage.app',
    measurementId: 'G-8CXLRLQ154',
  );
}
